schema_type: mlcube_invoke
schema_version: 1.0.0

task_name: train

input_binding:
        data_dir: $WORKSPACE/data
        parameters_file: $WORKSPACE/parameters/default.parameters.yaml
        model_in: $WORKSPACE/model

output_binding:
        log_dir: $WORKSPACE/train_logs
        metrics: $WORKSPACE/metrics/train_metrics.json
        model_dir: $WORKSPACE/model
