# Here you can define new parameters
MY_NEW_PARAMETER_EXAMPLE: "*Example*"
# author info
AUTHOR_NAME: "Chuck Norris"
AUTHOR_EMAIL: "chuck@norris.org"
# put your app name here
APPLICATION_NAME: "AMAZING APPLICATION"
# specify version here, if possible use semantic versioning
APPLICATION_VERSION: "0.0.1"