# Schema
schema_version: 1.0.0
schema_type: mlcube_task

# Task Inputs
inputs: []

# Task Outputs
outputs:
        - name: metrics
          type: file

        - name: model_dir
          type: directory
        
        - name: log_dir
          type: directory